name: "OpenAI PR Review"
author: "cawcaw253"
description: "Pull Request code review action with OpenAI"
branding:
  icon: "aperture"
  color: "black"

inputs:
  OPENAI_API_KEY:
    description: "OpenAI Key for API call"
    required: true
  GITHUB_TOKEN:
    description: "Token for checkout code and leave comment"
    required: true
  LANGUAGE:
    description: "Language for comments"
    required: false
    default: "English"
  MODEL:
    description: "Model for chat completion"
    required: false
    default: "gpt-3.5-turbo"

runs:
  using: "node16"
  main: "dist/index.js"
