name: "OpenAI PR Review"
author: "detectiveCrow"
description: "Pull Request code review action with OpenAI"
branding:
  icon: "aperture"
  color: "black"

inputs:
  OPENAI_API_KEY:
    description: "OpenAI Key for API call"
    required: true
  GITHUB_TOKEN:
    description: "Token for checkout code and leave comment"
    required: true
  LANGUAGE:
    description: "Language for comments"
    required: false
    default: "English"
  MODEL:
    description: "Model for chat completion"
    required: false
    default: "gpt-3.5-turbo-0301"

runs:
  using: docker
  image: Dockerfile
  env:
    OPENAI_API_KEY: ${{ inputs.OPENAI_API_KEY }}
    GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
    LANGUAGE: ${{ inputs.LANGUAGE }}
    MODEL: ${{ inputs.MODEL }}
