name: Release Action

on:
  push:
    branches:
      - master

jobs:
  create-release:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Release action
      uses: ncipollo/release-action@v1
      with:
        bodyFile: "release/note.md"
        tag: "v1.0.1"
