name: Release Action

on:
  push:
    branches:
      - master

jobs:
  release-action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - uses: go-semantic-release/action@v1
      with:
        github-token: ${{ secrets.GH_PAT }}
