name: Release Action

on:
  pull_request:
    types: [closed]

jobs:
  create-release:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Release action
      uses: ncipollo/release-action@v1
      with:
        bodyFile: "release/note.md"
        tag: "v1.0.0"
