name: Test Action

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    name: test action
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: OpenAI review released version
        uses: detectiveCrow/ai-review-action@latest
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: "english"

      - name: OpenAI review current branch
        uses: ./
        id: review
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          LANGUAGE: "korean"

      - name: Delete Review Comments
        uses: izhangzhihao/delete-comment@master
        with: 
          github_token: ${{ secrets.GH_PAT }}
          delete_user_name: ${{ secrets.GH_UN }}
          issue_number: ${{ github.event.number }}
